#
# Jekyll configuration
#
exclude: ["vendor", "2010", "2011", "2012", "2013"]

markdown: kramdown

encoding: utf-8

collections:
    2014_program:
            output: true
            permalink: /2014/program/sessions/:path:output_ext
    2015_program:
            output: true
            permalink: /2014/program/sessions/:path:output_ext

tracks2013:
    13_agile: Agile
    13_bigdata: BigData / noSQL
    13_fun_prog: Programmation Fonctionnelle
    13_gamification: Gamification
    13_ia_robotics: IA / Robotique
    13_java: Java
    13_microsoft: Microsoft
    13_mobile: Mobile
    13_ruby: Ruby / Rails
    13_web_dev: Web (JS / CSS3 / HTML5)
    13_incubator: Incubateur

hours_j1:
- "9:40<br /><br />10:25"
- "10:40<br /><br />11:25"
- "11:40<br /><br />12:25"
- "13:30<br /><br />14:15"
- "14:30<br /><br />15:15"
- "15:30<br /><br />16:15"
- "16:30<br /><br />17:15"
- "17:30<br /><br />18:15"

hours_j2:
- "9:40<br /><br />10:25"
- "10:40<br /><br />11:25"
- "11:40<br /><br />12:25"
- "13:30<br /><br />14:15"
- "14:30<br /><br />15:15"
- "15:30<br /><br />16:15"

schedule2013_j1:
- 13_agile
- 13_fun_prog
- 13_java
- 13_microsoft
- 13_mobile
- 13_web_dev
- 13_incubator
- 13_gamification
- 13_bigdata

schedule2013_j2:
- 13_agile
- 13_fun_prog
- 13_java
- 13_microsoft
- 13_mobile
- 13_web_dev
- 13_incubator
- 13_ruby
- 13_ia_robotics

schedule2014:
    - "10:30 - 11:15"
    - "11:30 - 12:15"
    - "13:45 - 14:30"
    - "14:45 - 15:30"
    - "16:00 - 16:45"
    - "17:00 - 17:45"

schedule2015:
    - "10:30"
    - "11:30"
    - "13:45"
    - "14:45"
    - "16:00"
    - "17:00"
